
title: Miguel Garcia-Duch
page-top-title: Miguel Garcia
top-section-bg-text: Computer Science
home-subtitle: Miguel Garcia-Duch&ensp;|&ensp;李森
copyright-text: '&copy; Miguel Garcia-Duch 2023. All Rights Reserved.'
